### ISSUE TITLE
When running 'python data.py', error appears about name Matrix MT"

### ISSUE THREAD

**Issue by thudepwcp13** [bostondiditeam/MV3D#14]
Traceback (most recent call last):
  File "data.py", line 644, in <module>
    preproces(data_dir, frames_index)
  File "data.py", line 565, in preproces
    data_in_single_driver(cfg.RAW_DATA_SETS_DIR, key, driver, frames_index)
  File "data.py", line 493, in data_in_single_driver
    dump_bbox_on_camera_image(save_preprocess_dir, dataset, objects, date, drive, frames_index, overwrite=True)
  File "data.py", line 394, in dump_bbox_on_camera_image
    img = draw.draw_box3d_on_camera(rgb, gt_boxes3d)
  File "/home/wuchengpeng/MV3D/src/net/utility/draw.py", line 35, in draw_box3d_on_camera
    projections = box3d.box3d_to_rgb_box(boxes3d)
  File "/home/wuchengpeng/MV3D/src/net/processing/boxes3d.py", line 120, in box3d_to_rgb_box
    if Mt is None: Mt = np.array(MATRIX_Mt)
NameError: name 'MATRIX_Mt' is not defined

So, I search the data.py, boxes3d.py, draw.py, but I don't find the definition of MATRIX_MT and MATRIX_KT, where are them?

**Comment by junwenchen** [comment]
@thudepwcp13 I have the same problem. Have you solved it?

**Comment by lihua213** [comment]
@thudepwcp13 @junwenchen 
#rgb camera
MATRIX_Mt = ([[  2.34773698e-04,   1.04494074e-02,   9.99945389e-01,  0.00000000e+00],
              [ -9.99944155e-01,   1.05653536e-02,   1.24365378e-04,  0.00000000e+00],
              [ -1.05634778e-02,  -9.99889574e-01,   1.04513030e-02,  0.00000000e+00],
              [  5.93721868e-02,  -7.51087914e-02,  -2.72132796e-01,  1.00000000e+00]])

MATRIX_Kt = ([[ 721.5377,    0.    ,    0.    ],
              [   0.    ,  721.5377,    0.    ],
              [ 609.5593,  172.854 ,    1.    ]])

**Comment by ghost** [comment]
You can define MATRIX_Mt and MATRIX_Kt in the configuration file, i.e. config.py

**Comment by Anida-qin** [comment]
@thudepwcp13 @Fafadada 
hi~
I m new in 3d object detection.
How did we get the MATRIX_Mt and MATRIX_Kt ? What does it mean ? It troubles me for some time.
I think when we detect the box3d, the only thing needs to do is to multiply project matrix. And the project matrix should be 4*3. In addition, I didn't find same number in calib_cam_to_cam.txt and calib_velo_to_cam.txt and calib_imu_to_velo.txt.
Could u help me ? Thanks a lot.
