### ISSUE TITLE
errors when running python train.py

### ISSUE THREAD

**Issue by liumeng99** [bostondiditeam/MV3D#16]
Using TensorFlow backend.
Namespace(continue_train=False, max_iter=1000, tag='unknown_tag', targets='top_view_rpn,image_feature,fusion', weights='')

Enter log tag : 1
Set log tag :"1" ok !!
Traceback (most recent call last):
  File "train.py", line 106, in <module>
    data_splitter = TrainingValDataSplitter(training_dataset)
  File "/home1/liumeng/MV3D/src/utils/training_validation_data_splitter.py", line 44, in __init__
    self.split_bags_by_tag_name()
  File "/home1/liumeng/MV3D/src/utils/training_validation_data_splitter.py", line 65, in split_bags_by_tag_name
    self.bags = shuffle(self.bags, random_state=0)
  File "/home/deepwork/workspace/tensorflow-env-vary/tensorflow1.0-py3.5/lib/python3.5/site-packages/sklearn/utils/__init__.py", line 343, in shuffle
    return resample(*arrays, **options)
  File "/home/deepwork/workspace/tensorflow-env-vary/tensorflow1.0-py3.5/lib/python3.5/site-packages/sklearn/utils/__init__.py", line 269, in resample
    resampled_arrays = [safe_indexing(a, indices) for a in arrays]
  File "/home/deepwork/workspace/tensorflow-env-vary/tensorflow1.0-py3.5/lib/python3.5/site-packages/sklearn/utils/__init__.py", line 269, in <listcomp>
    resampled_arrays = [safe_indexing(a, indices) for a in arrays]
  File "/home/deepwork/workspace/tensorflow-env-vary/tensorflow1.0-py3.5/lib/python3.5/site-packages/sklearn/utils/__init__.py", line 164, in safe_indexing
    return [X[idx] for idx in indices]
  File "/home/deepwork/workspace/tensorflow-env-vary/tensorflow1.0-py3.5/lib/python3.5/site-packages/sklearn/utils/__init__.py", line 164, in <listcomp>
    return [X[idx] for idx in indices]
KeyError: 0

@zxf8665905  @lancejchen

**Comment by liumeng99** [comment]
what tag should I enter ?

**Comment by adioshun** [comment]
in my case, any number is ok. (eg. 1)  I didn't have got the error like yours.

**Comment by jeasinema** [comment]
This tag is for logging and pre-trained weight searching, so any valid string is ok, but be sure to remember that.

**Comment by salmanahmedshaikh** [comment]
In train.py, I am getting the following error. Why the tag_size is zero??

Namespace(continue_train=False, max_iter=1000, tag='unknown_tag', targets='top_view_rpn,image_feature,fusion', weights='')

Enter log tag : 1

Set log tag :"1" ok !!

Traceback (most recent call last):
  File "train.py", line 208, in <module>
    data_splitter = TrainingValDataSplitter(train_n_val_dataset)
  File "/home/salman/Development/MV3D/src/utils/training_validation_data_splitter.py", line 44, in __init__
    self.split_bags_by_tag_name()
  File "/home/salman/Development/MV3D/src/utils/training_validation_data_splitter.py", line 125, in split_bags_by_tag_name
    self.real_split_rate = 1. * split_point / tag_size
ZeroDivisionError: float division by zero

**Comment by wqlu** [comment]
> In train.py, I am getting the following error. Why the tag_size is zero??
> 
> Namespace(continue_train=False, max_iter=1000, tag='unknown_tag', targets='top_view_rpn,image_feature,fusion', weights='')
> 
> Enter log tag : 1
> 
> Set log tag :"1" ok !!
> 
> Traceback (most recent call last):
> File "train.py", line 208, in 
> data_splitter = TrainingValDataSplitter(train_n_val_dataset)
> File "/home/salman/Development/MV3D/src/utils/training_validation_data_splitter.py", line 44, in **init**
> self.split_bags_by_tag_name()
> File "/home/salman/Development/MV3D/src/utils/training_validation_data_splitter.py", line 125, in split_bags_by_tag_name
> self.real_split_rate = 1. * split_point / tag_size
> ZeroDivisionError: float division by zero

i think you can try to  change 'train_n_val_dataset' list in src/train.py,  you may not have some file directories.
