### ISSUE TITLE
When i run "python data.py" in anaconda, I meet a read_objects error ! Thank you for your response。

### ISSUE THREAD

**Issue by FightStone** [bostondiditeam/MV3D#33]
I run "python data.py" in anaconda, i meet a trouble as follow : 

    here:  ./src/lidar_data_preprocess/Python_to_C_Interface/ver3/LidarTopPreprocess.so
    data.py: calling main function ... 
    date 2011_09_26 and driver 0001
    Traceback (most recent call last):
      File "./src/data.py", line 779, in <module>
        preproces(data_dir, frames_index)
      File "./src/data.py", line 703, in preproces
        data_in_single_driver(cfg.RAW_DATA_SETS_DIR, key, driver, frames_index)
      File "./src/data.py", line 597, in data_in_single_driver
        raise ValueError('read_objects error!!!!!')
    ValueError: read_objects error!!!!!

Because of the data set I put in anaconda, the program could not be found? 
Or did I not place the data set in the specified file format order ?
Who can tell me the reason? Thank you very much !

**Comment by FightStone** [comment]
I solved this problem. This error was caused by a error file name of data sets .

**Comment by fted** [comment]
I am new to this and just experimenting to learn, but seem to get stuck with this exact error message.
How did you solve this issue, and what was the problem?

**Comment by phamquandung** [comment]
> I solved this problem. This error was caused by a error file name of data sets .

Could you please help me? I tried to run this program some days but I still meet these errors. I dont know how to solve it

**Comment by vllsm** [comment]
Hi, I am facing the same problem, I tested the condition before (data.py line 591) the return of os.path.isfile(tracklet_file) is also True, is there anyone who can help me with this, thx so much

**Comment by WUT-xiaoming** [comment]
Could you please help me?same problem

**Comment by DonghoonPark12** [comment]
More kitti folder file is needed.
Not only '0001' file. Don't forget to download 'tracklet file' also.
['0001', '0017', '0029', '0052', '0070', '0002', '0018', '0035', '0056', '0079', '0019', '0036', '0005', '0057', '0084', '0020', '0039', '0059', '0086', '0011', '0023', '0046', '0060', '0091', '0013', '0027', '0048', '0061', '0015', '0028', '0051', '0064']
you can download [here](http://www.cvlibs.net/datasets/kitti/raw_data.php?type=residential).

**Comment by Jing-jingok** [comment]
> > I solved this problem. This error was caused by a error file name of data sets .
> 
> Could you please help me? I tried to run this program some days but I still meet these errors. I dont know how to solve it

I have the same error,can you help me
